---
id: Http
name: Http
full: HTTP client library
description: A library for making HTTP requests.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Http
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha1
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: BSD-2-Clause
  uri: http://www.horde.org/licenses/bsd
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/Horde_Exception: ^2
      pear.horde.org/Horde_Support: ^2
  optional:
    pear:
      pear.horde.org/Horde_Test: ^2.1
      pecl.php.net/pecl_http:
        version: ^1.7 || ^2 || ^3
        providesextension: http
    ext:
      curl: '*'
